before_script:
  - echo "starting build..."
  - echo "Restoring NuGet Packages..."
  - dotnet restore HospitalManagement.sln
  - C:\Users\zenor\Downloads\nuget.exe restore

stages:
  - build
  - test

build:
  stage: build
  script:
  - echo "Release build..."
  - dotnet build --configuration Release HospitalManagement.sln
  artifacts:
    untracked: true

test:
  stage: test
  script:
  - echo "starting tests"
  - cd HospitalTests\bin\Release
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe HospitalTests.dll
  dependencies:
  - build
